### ISSUE TITLE
選項隨機

### ISSUE THREAD

**Issue by Yuessiah** [ccns/quiz-chatbot-server#1]
雖然讓前端寫也行
但是後端做的話功能上比較理想

很閒的話再做吧, 這也不是很重要的功能

**Comment by GHolk** [comment]
要在匯入題目的時候直接把選項弄亂。

如果每次給題目都隨機，
會不知道回答的時哪一次的隨機結果。

**Comment by d4n1elchen** [comment]
我覺得前端（機器人）做比較理想，後端維持一樣的答案就好

**Comment by Yuessiah** [comment]
其實就是要做到外人不知道是哪個隨機答案 (沒辦法寫沒關係啦
這是我說的功能上比較理想
.
前端比後端理想的點是..?

**Comment by d4n1elchen** [comment]
前端排選項的時候打亂就好啦

**Comment by Yuessiah** [comment]
ㄛ 好窩༼ つ◕_◕ ༽つ
